version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: shopper
      POSTGRES_PASSWORD: shopper
      POSTGRES_DB: shopper
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    container_name: backend
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_GOOGLE_MAPS_API_KEY: ${GOOGLE_API_KEY}
    container_name: frontend
    environment:
      CHOKIDAR_USEPOLLING: "true" 
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
